import type { Metadata } from "next";
import "./globals.css";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import React, {FC, ReactNode} from "react";
import { Layout, Menu } from "antd";
import { Content, Footer, Header } from "antd/es/layout/layout";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
    children: ReactNode[];
};

const items = [
    { key: 0, label: <Link href={"/"}>Home</Link> },
    { key: 1, label: <Link href={"/posts"}>Posts</Link> },
    { key: 2, label: <Link href={"/albums"}>Albums</Link> },
    { key: 3, label: <Link href={"/todos"}>Todos</Link> },
];

const RootLayout: FC<Props> = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
            <Layout className="layout">
                <Header className="header">
                    <Menu
                        theme="dark"
                        mode="horizontal"
                        defaultSelectedKeys={["0"]}
                        items={items}
                        style={{ flex: 1, minWidth: 0 }}
                    />
                </Header>
                <Content className="content">{children}</Content>
                <Footer className="footer">Footer</Footer>
            </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}

export default RootLayout;
